### ISSUE TITLE
Launching in OpenStax?

### ISSUE THREAD

**Issue by GitHubGreg** [openstax/simulations#452]
Sorry that this is not a bug, but I am curious about the fate of these excellent simulations. The OpenStax Physics textbook links to an old Java Phet simulation, whereas you've got a great HTML5 sim in this repo. Thanks!

**Comment by openstaxalina** [comment]
Hi Greg, thank you for getting in touch!
Could you point me to where you are viewing the content linking to the old Java PhET simulation?  

Thank you,
Alina Slavik
Associate Director, Content Development

**Comment by GitHubGreg** [comment]
I can’t find it now but I had found it when posting originally. But I see it’s not on the official site so never mind that:
https://cnx.org/contents/rydUIGBQ@12.1:EW-vVPuy@6/6-2-Photoelectric-Effect

But then I’m still unclear on why your site doesn’t include the sims in this repo.

**Comment by openstaxalina** [comment]
Hi again Greg,

Actually, you did find one of our official sites - OpenStax CNX (cnx.org) is the repository where the webview format for all our books is housed.  There is also lots of great community-created content in the repository.

I'm having trouble locating the link to the simulation in the _University Physics_ module you linked, but our _College Physics_ book does embed the simulations in this repo.  "Moving Man" is an example at the end of this module: https://cnx.org/contents/Ax2o07Ul@14.79:YCO4fVoo@9/2-4-Acceleration.
(We are still resolving some issues with display to allow the buttons to resize so that they do not overlap.)  

Thanks so much for using OpenStax resources.  Please let us know if there is anything else that we can help with.

-Alina

**Comment by GitHubGreg** [comment]
Great to know you are using them. I was worried they'd been abandoned.
Thanks.
